MEXC:
  BEARER: "AAAAAAAAAAAAAAAAAAAAAMv%2BbAEAAAAAQaD%2FOm2wMCRk51w24NsuH9kCUas%3DRgHNe9kFGzLihHVVjoddLIIcLd5JZqsY7ZI5ZEfdxs7R7GGdhL"
  API_KEY: "cZFeWNAeCCyh97oYb2fEqqEIR"
  API_KEY_SECRET: "3fDR0SZWQcoBDZm0QbKDywihF8ZrWXEG9nd91euaMTMyq18ULD"
